#!/bin/sh

#dscl . -create /Users/markus
#dscl . -create /Users/markus NFSHomeDirectory /Users/markus
#dscl . -create /Users/markus PrimaryGroupID 20
#dscl . -create /Users/markus RealName "Markus Mauthe"
#dscl . -create /Users/markus UniqueID 555
#dscl . -create /Users/markus UserShell /bin/zsh
#dscl . -passwd /Users/markus DeepPurple
#dscl . -append /Groups/admin GroupMembership markus

#./userpic.sh markus markus.jpg

exit 0

osascript closeAllApps.scpt
