.
| (.sources[] | select(.name == "External").settings.device) = "0x2543000043e9a4d"
| (.sources[] | select(.name == "Internal").settings.device) = "0x8020000005ac8514"

| (.sources[] | select(.name == "Intro").settings.local_file) = "/Users/markus/Documents/DieWeltImBlick/intro"
| (.sources[] | select(.name == "Outro").settings.local_file) = "/Users/markus/Documents/DieWeltImBlick/outro"
| (.sources[] | select(.name == "Video").settings.local_file) = "/Users/markus/Documents/DieWeltImBlick/video"

# demo
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0001_17065.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0001_17123.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0001_17178.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0004.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0004_16406.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0004_17126.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0006.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0006_16616.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0006_17095.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0007_16374.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0007_16798.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0007_17071.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0007_17242.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0008_17130.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0010_16400.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0011_17075.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0012_16622.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0013_17135.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0014_16581.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0014_17078.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0015_16417.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0016_16610.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0016_16804.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0016_17138.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0016_17289.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0017_16626.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0017_17724.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0020_17058.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0020_17674.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0021_17463.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0022_16630.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0023_16389.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0023_17306.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0023_17730.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0025_16911.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0027_17150.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0028_16895.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0028_17608.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0029_17017.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0030_17471.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0031_16747.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0031_17314.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0035_16820.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0037_17320.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0038_17269.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0040_17270.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0041_16650.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0042_17272.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0043_17163.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0046_16441.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0051_17167.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0052_17335.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0057_17340.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0060_16665.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0060_17343.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0063_17702.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0064_17637.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0066_17444.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0067_16459.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0069_17540.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0072_16672.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0074_17543.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0084_17551.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0085_16964.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0087_16559.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0089_16479.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0093_16565.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0098_16692.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0099.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0100_16867.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0104_16697.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0104_16982.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0121_16714.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0122_17767.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0124_17769.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0130_17774.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0135_17585.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0140.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/DSC_0163.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/Retezat_0132.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/Rumaenien_9837.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/Rumaenien_9838.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/Rumaenien_9864.jpg"}]
