.
| (.sources[] | select(.name == "External").settings.device) = "0x2543000043e9a4d"
| (.sources[] | select(.name == "Internal").settings.device) = "0x8020000005ac8514"

| (.sources[] | select(.name == "Intro").settings.local_file) = "/Users/markus/Documents/DieWeltImBlick/intro"
| (.sources[] | select(.name == "Outro").settings.local_file) = "/Users/markus/Documents/DieWeltImBlick/outro"
| (.sources[] | select(.name == "Video").settings.local_file) = "/Users/markus/Documents/DieWeltImBlick/video"

# show
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/01.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/02.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/03.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/04.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/05.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/06.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/07.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/08.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/09.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/10.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/11.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/12.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/13.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/14.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/15.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/16.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/17.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/18.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/19.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/20.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/21.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/22.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/23.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/24.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/25.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/26.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/27.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/28.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/29.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/30.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/31.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/32.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/33.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/34.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/35.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/36.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/37.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/38.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/39.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/40.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/41.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/42.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/43.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/44.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/45.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/46.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/47.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/48.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/49.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/50.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/51.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/52.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/53.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/54.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/55.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/56.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/57.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/58.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/59.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/60.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/61.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/62.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/63.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/64.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/65.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/66.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/67.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/68.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/69.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/70.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/71.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/72.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/73.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/74.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/75.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/76.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/77.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/78.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/79.jpg"}]
| (.sources[] | select(.id == "slideshow").settings.files) |= . + [{"value":"/Users/markus/Documents/DieWeltImBlick/Patagonien/80.jpg"}]
