#!/bin/sh

chown -R $USER /tmp/obs-studio 

OBS="Library/Application Support/obs-studio"

mkdir -p ~/.hammerspoon
mv /tmp/obs-studio/init.lua ~/.hammerspoon

mv /tmp/obs-studio ~/"$OBS"

find ~/"$OBS" -d -exec touch -ht 197304291400 '{}' \;

exit 0
