#!/bin/sh

OBS="Library/Application Support/obs-studio"
UPDeck="Library/Application Support/UPDeck"

chown -R $USER /tmp/obs-studio

mkdir -p ~/.hammerspoon
mv /tmp/obs-studio/init.lua ~/.hammerspoon

find ~/.hammerspoon -d -exec touch -ht 197304291400 '{}' \;
chown -R root ~/.hammerspoon

mv /tmp/obs-studio ~/"$OBS"

chmod +w ~/"$OBS"
chmod +w ~/"$OBS/basic/scenes"
chown -R root ~/"$OBS"/basic/profiles

find ~/"$OBS" -d -exec touch -ht 197304291400 '{}' \;

open -b org.hammerspoon.Hammerspoon

exit 0
