#!/bin/sh

OBS="Library/Application Support/obs-studio"

killall obs

rm -rf ~/"$OBS"

#
# maintenance
#
cp ~/"Documents/Die Welt im Blick - Online Show /Trailer/Intro NE 1 - Zugabe.mov" ~/Documents/DieWeltImBlick/intro.mov

chmod -w ~/Documents/DieWeltImBlick/outro.mov
chown root ~/Documents/DieWeltImBlick/outro.mov
find ~/Documents/DieWeltImBlick -d -exec touch -ht 197304291400 '{}' \;

find ~ -name "DTV_GPOP022_089.mov" -delete

rm -rf /Users/*/"$OBS" /"$OBS"
#
# maintenance
#

exit 0
